---
- name: Auto_authorized_keys
  hosts: node
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: create key
      connection: local
      command: "ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ''"
      ignore_errors: yes
      run_once: true

    - name: input key
      authorized_key:
        user: ec2-user
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"