## change Local resource
resource "local_file" "tf_ansible_vars" {
  content = <<-DOC
    ---
    # Ansible vars_file containing variable values from Terraform.
    # Generated by Terraform mgmt configuration.

    nginx:
      elb_domain: ${aws_lb.ex_alb.dns_name}
      nginx_path: /etc/nginx
    DOC
  filename = "./ansible/role/nginx/vars/main.yml"
}