## change Local resource
resource "local_file" "tf_ansible_nginx_vars" {
  content = <<-DOC
    ---
    # Ansible vars_file containing variable values from Terraform.
    # Generated by Terraform mgmt configuration.

    nginx:
      elb_domain: ${aws_lb.ex_alb.dns_name}
      nginx_path: /etc/nginx
    DOC
  filename = "./ansible/role/nginx/vars/main.yml"
}

resource "local_file" "tf_ansible_mysql_vars" {
  content = <<-DOC
    ---
    # Ansible vars_file containing variable values from Terraform.
    # Generated by Terraform mgmt configuration.

    mysql:
      admin_password: ${var.my_db_password}
      db_user: ${var.my_db_user}
      db_host_list:
        db_1: ${aws_db_instance.my_db[0].address}
        db_2: ${aws_db_instance.my_db[1].address}
    DOC
  filename = "./ansible/role/mysql/vars/main.yml"
}