# tasks file for install_flask
---
- name: flask environment
  copy:
    src: /home/ec2-user/ansible/role/install_flask/files/flask_env.sh
    dest: ~/flask_env.sh
    owner: ec2-user
    group: ec2-user
    mode: '0775'

- name: install git
  become: yes
  yum:
    name: git
    state: present

- name: Create project directory
  file:
    path: /home/ec2-user/myproject
    state: directory

- name: Clone a repo with separate git directory
  git:
    repo: https://github.com/iamjjanga-ouo/flask_connect_mysql.git
    dest: /home/ec2-user/myproject

- name: Execute flask_env.sh
  command: bash flask_env.sh

- name: pip install requirement.txt
  pip:
    requirements: ~/myproject/requirement.txt
    virtualenv: ~/myproject/venv
