---
- name: Install nginx, flask on the nodes
  hosts: node

  roles:
    - { role: ./role/mysql }
    - { role: ./role/flask }
    - { role: ./role/nginx }

  tasks:
    - name: Restart myproject service
      become: yes
      command: systemctl restart myproject