# tasks file for flask
---
- name: Disable SELinux
  become: yes
  selinux:
    state: disabled

- name: Install python3
  become: yes
  action: "{{ ansible_pkg_mgr }} name=python3 state=present"

- name: Create project directory
  file:
    path: /home/ec2-user/myproject
    state: directory

- name: install git
  become: yes
  yum:
    name: git
    state: present

- name: Clone a repo with separate git directory
  git:
    repo: https://github.com/iamjjanga-ouo/flask_connect_mysql.git
    dest: /home/ec2-user/myproject
    update: no           # when change in local repo, don't update

- name: flask environment
  copy:
    src: /home/ec2-user/ansible/role/flask/files/flask_env.sh
    dest: ~/flask_env.sh
    owner: ec2-user
    group: ec2-user
    mode: '0775'

- name: Execute flask_env.sh
  command: bash flask_env.sh

- name: pip install requirement.txt
  pip:
    requirements: ~/myproject/requirement.txt
    virtualenv: ~/myproject/venv

- name: Copy file for Environment variables (.env)
  command: "cp /home/ec2-user/env_tmp /home/ec2-user/myproject/.env"
  ignore_errors: true

- name: After copy, delete env_tmp file
  file:
    path: /home/ec2-user/env_tmp
    state: absent

- name: Create Systemd Unit File
  become: yes
  file:
    path: /etc/systemd/system/myproject.service
    state: touch
    mode: o=rw,g=r,o=r

- name: Configure myproject.service
  become: yes
  lineinfile:
    dest: /etc/systemd/system/myproject.service
    line: "{{ item }}"
  with_items:
    - "[Unit]"
    - "Description=Gunicorn instance to serve myproject"
    - "After=network.target"
    - "[Service]"
    - "User=ec2-user"
    - "Group=nginx"
    - "WorkingDirectory=/home/ec2-user/myproject"
    - "Environment='PATH=/home/ec2-user/myproject/venv/bin'"
    - "ExecStart=/home/ec2-user/myproject/venv/bin/gunicorn --workers 3 --bind unix:myproject.sock -m 007 wsgi"
    - "[Install]"
    - "WantedBy=multi-user.target"

- name: Start and enable myproject service
  become: yes
  systemd:
    name: myproject
    enabled: yes
    state: started