---
# handlers file for nginx
- name: start nginx web server
  become: yes
  become_user: root
  systemd: name=nginx state=started

- name: restart nginx web server
  become: yes
  become_user: root
  systemd: name=nginx state=restarted
